# theme: jekyll-theme-leap-day
title: Engineering Challenges and Innovations in Disney+ Hotstar
description: In our portfolio, we focus on content delivery, user experience optimization, and data structures for Disney+ Hotstar.
show_downloads: false
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
